In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
!pip install matplotlib

In [8]:
df = pd.read_csv(r"C:\Users\ELCOT\Downloads\Customer_Churn.csv")

In [9]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [10]:
df.shape

(7043, 21)

In [11]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [13]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["TotalCharges"].head(10)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: str

In [16]:
df["TotalCharges"].tail(10)

7033    2625.25
7034    6886.25
7035     1495.1
7036      743.3
7037     1419.4
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, dtype: str

In [17]:
df["TotalCharges"].unique()[:20]

<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',  '587.45',   '326.8',  '5681.1',  '5036.3',
 '2686.05', '7895.15', '1022.95', '7382.25',  '528.35',  '1862.9']
Length: 20, dtype: str

In [18]:
(df["TotalCharges"].str.strip() == "").sum()

np.int64(11)

In [19]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [11]:
df.loc[df["TotalCharges"].str.strip() == "", ["customerID", "tenure", "MonthlyCharges", "Contract", "Churn"]]

      customerID  tenure  MonthlyCharges  Contract Churn
488   4472-LVYGI       0           52.55  Two year    No
753   3115-CZMZD       0           20.25  Two year    No
936   5709-LVOEQ       0           80.85  Two year    No
1082  4367-NUYAO       0           25.75  Two year    No
1340  1371-DWPAZ       0           56.05  Two year    No
3331  7644-OMVMY       0           19.85  Two year    No
3826  3213-VVOLG       0           25.35  Two year    No
4380  2520-SGTTA       0           20.00  Two year    No
5218  2923-ARZLG       0           19.70  One year    No
6670  4075-WKNIU       0           73.35  Two year    No
6754  2775-SEFEE       0           61.90  Two year    No

In [13]:
df["TotalCharges"] = df["TotalCharges"].str.strip().replace("", "0")

In [14]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"])

In [23]:
df["TotalCharges"].dtype

dtype('float64')

In [24]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [25]:
(df["TotalCharges"] == 0).sum()

np.int64(11)

In [26]:
df["gender"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [27]:
df["Partner"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [28]:
df["Dependents"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [29]:
df["Contract"].unique()

<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

In [30]:
df["InternetService"].unique()

<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

In [31]:
df["Churn"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [32]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [33]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [34]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [15]:
df.columns = [
    "customer_id",
    "gender",
    "senior_citizen",
    "partner",
    "dependents",
    "tenure",
    "phone_service",
    "multiple_lines",
    "internet_service",
    "online_security",
    "online_backup",
    "device_protection",
    "tech_support",
    "streaming_tv",
    "streaming_movies",
    "contract",
    "paperless_billing",
    "payment_method",
    "monthly_charges",
    "total_charges",
    "churn"
]

In [36]:
df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='str')

In [37]:
df[["senior_citizen", "tenure", "monthly_charges", "total_charges"]].describe()

       senior_citizen       tenure  monthly_charges  total_charges
count     7043.000000  7043.000000      7043.000000    7043.000000
mean         0.162147    32.371149        64.761692    2279.734304
std          0.368612    24.559481        30.090047    2266.794470
min          0.000000     0.000000        18.250000       0.000000
25%          0.000000     9.000000        35.500000     398.550000
50%          0.000000    29.000000        70.350000    1394.550000
75%          0.000000    55.000000        89.850000    3786.600000
max          1.000000    72.000000       118.750000    8684.800000

In [38]:
df["senior_citizen"].value_counts()

senior_citizen
0    5901
1    1142
Name: count, dtype: int64

In [39]:
df["tenure"].min(), df["tenure"].max()

(np.int64(0), np.int64(72))

In [40]:
df[["senior_citizen", "tenure", "monthly_charges", "total_charges"]].describe()

       senior_citizen       tenure  monthly_charges  total_charges
count     7043.000000  7043.000000      7043.000000    7043.000000
mean         0.162147    32.371149        64.761692    2279.734304
std          0.368612    24.559481        30.090047    2266.794470
min          0.000000     0.000000        18.250000       0.000000
25%          0.000000     9.000000        35.500000     398.550000
50%          0.000000    29.000000        70.350000    1394.550000
75%          0.000000    55.000000        89.850000    3786.600000
max          1.000000    72.000000       118.750000    8684.800000

In [41]:
df["senior_citizen"].value_counts()

senior_citizen
0    5901
1    1142
Name: count, dtype: int64

In [42]:
df["tenure"].min(), df["tenure"].max()

(np.int64(0), np.int64(72))

In [43]:
df[(df["total_charges"] == 0) & (df["tenure"] > 0)]

Empty DataFrame
Columns: [customer_id, gender, senior_citizen, partner, dependents, tenure, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_tv, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges, churn]
Index: []

[0 rows x 21 columns]

In [44]:
df[(df["total_charges"] > 0) & (df["tenure"] == 0)]

Empty DataFrame
Columns: [customer_id, gender, senior_citizen, partner, dependents, tenure, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_tv, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges, churn]
Index: []

[0 rows x 21 columns]

In [45]:
df.to_csv("customer_churn_cleaned.csv", index=False)

In [46]:
import os
"customer_churn_cleaned.csv" in os.listdir()

True

In [47]:
df["churn"].value_counts()

churn
No     5174
Yes    1869
Name: count, dtype: int64

In [48]:
churn_rate = (df["churn"] == "Yes").mean() * 100
churn_rate

np.float64(26.536987079369588)

In [49]:
total_customers = len(df)

churned_customers = (df["churn"] == "Yes").sum()

retained_customers = (df["churn"] == "No").sum()

print("Total Customers:", total_customers)
print("Churned Customers:", churned_customers)
print("Retained Customers:", retained_customers)
print("Churn Rate:", round(churn_rate, 2), "%")

Total Customers: 7043
Churned Customers: 1869
Retained Customers: 5174
Churn Rate: 26.54 %

In [50]:
contract_analysis = (
    df.groupby("contract")
      .agg(
          total_customers=("customer_id", "count"),
          churned_customers=("churn", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

contract_analysis["churn_rate"] = (
    contract_analysis["churned_customers"]
    / contract_analysis["total_customers"]
    * 100
)

contract_analysis

         contract  total_customers  churned_customers  churn_rate
0  Month-to-month             3875               1655   42.709677
1        One year             1473                166   11.269518
2        Two year             1695                 48    2.831858

In [51]:
contract_analysis.sort_values("churn_rate", ascending=False)

         contract  total_customers  churned_customers  churn_rate
0  Month-to-month             3875               1655   42.709677
1        One year             1473                166   11.269518
2        Two year             1695                 48    2.831858

In [16]:
df["tenure_group"] = pd.cut(
    df["tenure"],
    bins=[-1, 12, 24, 48, 72],
    labels=["0-12 months", "13-24 months", "25-48 months", "49-72 months"]
)

df.groupby("tenure_group", observed=True)["churn"].apply(
    lambda x: (x == "Yes").mean() * 100
).round(2)

tenure_group
0-12 months     47.44
13-24 months    28.71
25-48 months    20.39
49-72 months     9.51
Name: churn, dtype: float64

In [53]:
payment_analysis = (
    df.groupby("payment_method")
      .agg(
          total_customers=("customer_id", "count"),
          churned_customers=("churn", lambda x: (x == "Yes").sum())
      )
)

payment_analysis["churn_rate"] = (
    payment_analysis["churned_customers"]
    / payment_analysis["total_customers"] * 100
).round(2)

payment_analysis.sort_values("churn_rate", ascending=False)

                           total_customers  churned_customers  churn_rate
payment_method
Electronic check                      2365               1071       45.29
Mailed check                          1612                308       19.11
Bank transfer (automatic)             1544                258       16.71
Credit card (automatic)               1522                232       15.24

In [54]:
internet_analysis = (
    df.groupby("internet_service")
      .agg(
          total_customers=("customer_id", "count"),
          churned_customers=("churn", lambda x: (x == "Yes").sum())
      )
)

internet_analysis["churn_rate"] = (
    internet_analysis["churned_customers"]
    / internet_analysis["total_customers"] * 100
).round(2)

internet_analysis.sort_values("churn_rate", ascending=False)

                  total_customers  churned_customers  churn_rate
internet_service
Fiber optic                  3096               1297       41.89
DSL                          2421                459       18.96
No                           1526                113        7.40

In [17]:
df["monthly_charge_group"] = pd.cut(
    df["monthly_charges"],
    bins=[0, 40, 70, 100, float("inf")],
    labels=["Low", "Medium", "High", "Very High"]
)

charge_analysis = (
    df.groupby("monthly_charge_group", observed=True)
      .agg(
          total_customers=("customer_id", "count"),
          churned_customers=("churn", lambda x: (x == "Yes").sum())
      )
)

charge_analysis["churn_rate"] = (
    charge_analysis["churned_customers"]
    / charge_analysis["total_customers"] * 100
).round(2)

charge_analysis

                      total_customers  churned_customers  churn_rate
monthly_charge_group
Low                              1838                214       11.64
Medium                           1622                388       23.92
High                             2681               1014       37.82
Very High                         902                253       28.05

In [18]:
service_columns = [
    "online_security",
    "online_backup",
    "device_protection",
    "tech_support",
    "streaming_tv",
    "streaming_movies"
]

df["total_services"] = (
    df[service_columns]
    .apply(lambda x: (x == "Yes").sum(), axis=1)
)

df[["customer_id", "total_services"]].head(10)

  customer_id  total_services
0  7590-VHVEG               1
1  5575-GNVDE               2
2  3668-QPYBK               2
3  7795-CFOCW               3
4  9237-HQITU               0
5  9305-CDSKC               3
6  1452-KIOVK               2
7  6713-OKOMC               1
8  7892-POOKP               4
9  6388-TABGU               2

In [19]:
avg_monthly_charge = df["monthly_charges"].mean()

avg_monthly_charge

np.float64(64.76169246059918)

In [20]:
df["risk_segment"] = np.where(
    (df["contract"] == "Month-to-month") &
    (df["tenure"] <= 12) &
    (df["monthly_charges"] > avg_monthly_charge),
    "High Risk",
    "Other"
)

df["risk_segment"].value_counts()

risk_segment
Other        6064
High Risk     979
Name: count, dtype: int64

In [59]:
risk_analysis = (
    df.groupby("risk_segment")
      .agg(
          total_customers=("customer_id", "count"),
          churned_customers=("churn", lambda x: (x == "Yes").sum())
      )
)

risk_analysis["churn_rate"] = (
    risk_analysis["churned_customers"]
    / risk_analysis["total_customers"] * 100
).round(2)

risk_analysis

              total_customers  churned_customers  churn_rate
risk_segment
High Risk                 979                661       67.52
Other                    6064               1208       19.92

In [60]:
df.shape

(7043, 25)

In [62]:
df.to_csv("customer_churn_final.csv", index=False)

In [63]:
import os

"customer_churn_final.csv" in os.listdir()

True

In [69]:
!pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.0.54)
Requirement already satisfied: mysql-connector-python in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (9.6.0)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (4.15.0)

In [70]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = "Dharani@26"
host = "localhost"
port = 3306
database = "customer_churn"

encoded_password = quote_plus(password)

engine = create_engine(
    f"mysql+mysqlconnector://{username}:{encoded_password}@{host}:{port}/{database}"
)

print("Engine created successfully!")

Engine created successfully!

In [71]:
with engine.connect() as connection:
    print("MySQL connection successful!")

MySQL connection successful!

In [72]:
df.to_sql(
    "churn_customers",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data successfully loaded into MySQL!")

Data successfully loaded into MySQL!

In [73]:
import pandas as pd

query = """
SELECT COUNT(*) AS total_customers
FROM churn_customers;
"""

result = pd.read_sql(query, engine)

result

   total_customers
0             7043

In [9]:
df.shape

(7043, 21)

In [10]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [12]:
df["TotalCharges"] = df["TotalCharges"].str.strip()

In [21]:
df.shape

(7043, 25)

In [22]:
df.to_csv("customer_churn_final.csv", index=False)

In [24]:
import os
"customer_churn_final.csv" in os.listdir()

True

In [25]:
# Check where the notebook is currently saving files
import os

# Show the current working folder
print(os.getcwd())

# Show the full path of the final CSV file
print(os.path.abspath("customer_churn_final.csv"))

C:\Users\ELCOT
C:\Users\ELCOT\customer_churn_final.csv

In [26]:
# Import the shutil library for copying files
import shutil

# Define the current location of our final CSV file
source_file = r"C:\Users\ELCOT\customer_churn_final.csv"

# Define the Downloads folder location
downloads_folder = r"C:\Users\ELCOT\Downloads"

# Copy the final CSV file into Downloads
shutil.copy(source_file, downloads_folder)

# Confirm that the file now exists in Downloads
print("File copied successfully!")
print(os.path.exists(r"C:\Users\ELCOT\Downloads\customer_churn_final.csv"))

File copied successfully!
True